package com.sain.icandy.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_hgaccount", "id", Hgaccount.class);
		arp.addMapping("t_hgurl", "id", Hgurl.class);
		arp.addMapping("t_host", "id", Host.class);
		arp.addMapping("t_send_result", "id", SendResult.class);
		arp.addMapping("t_sports_events", "id", SportsEvents.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

