package com.sain.icandy.model;

import com.sain.icandy.model.base.BaseHost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Host extends BaseHost<Host> {
	public static final Host dao = new Host();
}
