package com.sain.icandy.model;

import com.sain.icandy.model.base.BaseSendResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SendResult extends BaseSendResult<SendResult> {
	public static final SendResult dao = new SendResult();
}
