package com.sain.icandy.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHgaccount<M extends BaseHgaccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setHgUsername(java.lang.String hgUsername) {
		set("hg_username", hgUsername);
	}

	public java.lang.String getHgUsername() {
		return get("hg_username");
	}

	public void setHgPassword(java.lang.String hgPassword) {
		set("hg_password", hgPassword);
	}

	public java.lang.String getHgPassword() {
		return get("hg_password");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
