package com.sain.icandy.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSendResult<M extends BaseSendResult<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setHostId(java.lang.Integer hostId) {
		set("hostId", hostId);
	}

	public java.lang.Integer getHostId() {
		return get("hostId");
	}

	public void setHost(java.lang.String host) {
		set("host", host);
	}

	public java.lang.String getHost() {
		return get("host");
	}

	public void setSportsEventsId(java.lang.Integer sportsEventsId) {
		set("sports_events_id", sportsEventsId);
	}

	public java.lang.Integer getSportsEventsId() {
		return get("sports_events_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return get("result");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setFailedNum(java.lang.Integer failedNum) {
		set("failedNum", failedNum);
	}

	public java.lang.Integer getFailedNum() {
		return get("failedNum");
	}

}
